# Generated by Django 4.1.3 on 2022-11-04 16:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('date_released', models.DateField(default=datetime.datetime.today)),
                ('likes', models.IntegerField()),
                ('myartists_id', models.IntegerField()),
                ('Artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Lyrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('mysongs_id', models.IntegerField()),
                ('Songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.songs')),
            ],
        ),
    ]
